name: spending-tracker
services:
  test:
    image: busybox
    command: echo HW
#   application:
#     image:
#     networks:
#       - front-tier
#       - back-tier
#
  database:
    image: postgres:17
    ports:
      - 5432:5432
    # networks:
    #   - back-tier
    environment:
      POSTGRES_PASSWORD: mysupersecret
      POSTGRES_DB: spending-tracking
      # Defaults
      # POSTGRES_USER: postgres
      # PGDATA: /var/lib/postgresql/data

  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin:
    image: dpage/pgadmin4:8.12
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: mysupersecret
      PGADMIN_LISTEN_PORT: 80

# volumes:
#   database-data:
#
networks:
  front-tier: {}
  back-tier: {}

