services:
  spending-tracker:
    build: .
    image: spending-tracker:latest
    platform: linux/amd64
    container_name: spending-tracker-local
    environment:
      - DB_PATH=/app/data/spending_tracker.db
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    volumes:
      - ./.env:/app/.env:ro
      - ./local-data:/app/data
      - ./local-logs:/app/logs
    networks:
      - spending-tracker-local

networks:
  spending-tracker-local:
    driver: bridge
