[project]
name = "spending-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-telegram-bot>=21.9",
]

[project.scripts]
hello = "spending_tracker:hello"

# Some IDEs (at least JetBrains' ones) do not work property with the new package installation method used by pip.
# Using this config-settings we enable compat mode that fixes the problem.
[tool.uv.pip]
config-settings = { editable_mode = "compat" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
]
